main/urls.py
from django.conf import settings
from django.urls import include, path
from django.contrib import admin

from wagtail.admin import urls as wagtailadmin_urls
from wagtail.core import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

from search import views as search_views
from events import views as event_views

urlpatterns = [
    path('django-admin/', admin.site.urls),

    path('admin/', include(wagtailadmin_urls)),
    path('documents/', include(wagtaildocs_urls)),

    path('search/', search_views.search, name='search'),

    path('validate-booking/', event_views.validate_event_form),
    path('submit-event-booking/', event_views.submit_event_booking),
]


if settings.DEBUG:
    from django.conf.urls.static import static
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    # Serve static and media files from development server
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = urlpatterns + [
    # For anything not caught by a more specific rule above, hand over to
    # Wagtail's page serving mechanism. This should be the last pattern in
    # the list:
    path("", include(wagtail_urls)),

    # Alternatively, if you want Wagtail pages to be served from a subpath
    # of your site, rather than the site root:
    #    path("pages/", include(wagtail_urls)),
]

events/models.py
from datetime import date

from django.conf import settings
from django.core.validators import MinValueValidator, RegexValidator, EmailValidator
from django.db import models
from django.db.models import Model
from django.forms import ModelForm, Textarea
from wagtail.core.fields import RichTextField
from wagtail.admin.panels import FieldPanel
from wagtail.models import Orderable, Page

from main.helper_methods import append_sidebar_to_context


class EventsIndexPage(Page):
    intro = RichTextField(blank=True)

    content_panels = Page.content_panels + [
        FieldPanel('intro', classname="full")
    ]

    subpage_types = ['events.EventPage', ]

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request)
        events = self.get_children().live()
        context['events'] = events

        append_sidebar_to_context(context)

        return context


class EventBooking(Orderable):
    # region CONSTS
    PLAYER = 'PL'
    MONSTER = 'MN'
    STAFF = 'ST'

    PLAYER_TYPES = [
        (PLAYER, 'Player'),
        (MONSTER, 'Monster'),
        (STAFF, 'Staff')
    ]

    BEARS = 'B'
    DRAGONS = 'D'
    GRYPHONS = 'G'
    HARTS = 'H'
    JACKALS = 'J'
    LIONS = 'L'
    TARANTULAS = 'T'
    UNICORNS = 'U'
    VIPERS = 'V'
    WOLVES = 'W'

    FACTIONS = [
        (BEARS, 'Bears'),
        (DRAGONS, 'Dragons'),
        (GRYPHONS, 'Gryphons'),
        (HARTS, 'Harts'),
        (JACKALS, 'Jackals'),
        (LIONS, 'Lions'),
        (TARANTULAS, 'Tarantulas'),
        (UNICORNS, 'Unicorns'),
        (VIPERS, 'Vipers'),
        (WOLVES, 'Wolves'),
    ]
    # endregion

    event = models.ForeignKey('EventPage', on_delete=models.PROTECT)

    first_name = models.CharField(
        max_length=255, validators=[RegexValidator('^[\\D]*$', message='First name must contain non-digit characters')]
    )
    last_name = models.CharField(
        max_length=255, validators=[RegexValidator('^[\\D]*$', message='Last name must contain non-digit characters')]
    )
    email = models.EmailField(validators=[EmailValidator()])
    contact_number = models.CharField(
        max_length=15, validators=[RegexValidator('^\\+?[\\d-]*$', message='Must be valid phone number format')]
    )

    lt_player_id = models.CharField(
        max_length=15, blank=True, null=True,
        help_text='Required if you have an existing Lorien Trust character (otherwise no blue gold for you!)',
        validators=[RegexValidator('[\\d]', message='Must be valid Lorien Trust Player ID')]
    )
    player_type = models.CharField(max_length=2, choices=PLAYER_TYPES, default=PLAYER)

    character_name = models.CharField(max_length=255, blank=True, null=True)
    character_faction = models.CharField(max_length=1, choices=FACTIONS, verbose_name='Faction', blank=True, null=True)

    is_catering = models.BooleanField(verbose_name='YES, I want food!', default=False)
    has_paid = models.BooleanField(default=False)
    emergency_contact_name = models.CharField(
        max_length=255, validators=[RegexValidator('^[\\D]*$', message='Must contain only non-digit characters')]
    )
    emergency_contact_number = models.CharField(
        max_length=15, validators=[RegexValidator('^\\+?[\\d-]*$', message='Must be valid phone number format')]
    )
    home_address = models.TextField(blank=True)
    medical_information = models.TextField(blank=True)

    panels = [
        FieldPanel('event'),
        FieldPanel('first_name'),
        FieldPanel('last_name'),
        FieldPanel('email'),
        FieldPanel('contact_number'),
        FieldPanel('lt_player_id'),
        FieldPanel('player_type'),
        FieldPanel('character_name'),
        FieldPanel('character_faction'),
        FieldPanel('is_catering'),
        FieldPanel('has_paid'),
        FieldPanel('emergency_contact_name'),
        FieldPanel('emergency_contact_number'),
        FieldPanel('home_address'),
        FieldPanel('medical_information'),
    ]

    def __str__(self):
        booking_str = f"{self.first_name} {self.last_name}"

        if self.character_name:
            booking_str += f" ({self.character_name} - {self.get_character_faction_display()})"

        booking_str += f" [{self.get_player_type_display()}]"
        return booking_str


class EventBookingForm(ModelForm):
    error_class = 'is-danger'

    class Meta:
        model = EventBooking
        fields = [
            'first_name',
            'last_name',
            'email',
            'contact_number',
            'player_type',
            'lt_player_id',
            'player_type',
            'character_name',
            'character_faction',
            'is_catering',
            'emergency_contact_name',
            'emergency_contact_number',
            'home_address',
            'medical_information',
            'has_paid',
        ]
        widgets = {
            'home_address': Textarea(attrs={'rows': 3}),
            'medical_information': Textarea(attrs={'rows': 3}),
        }


class EventPage(Page):
    event_date = models.DateField(verbose_name="Event date")
    intro = models.CharField(max_length=250, default='')
    description = RichTextField(blank=True)
    details = RichTextField(blank=True)
    image = models.ForeignKey('wagtailimages.Image', on_delete=models.SET_NULL, null=True, related_name='+')
    player_limit = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    monster_limit = models.IntegerField(default=0, validators=[MinValueValidator(0)])
    player_cost = models.DecimalField(
        verbose_name='Player cost', default=0, max_digits=4, decimal_places=2, validators=[MinValueValidator(0)]
    )
    monster_cost = models.DecimalField(
        verbose_name='Monster cost', default=0, max_digits=4, decimal_places=2, validators=[MinValueValidator(0)]
    )
    player_catering_cost = models.DecimalField(
        verbose_name='Player catering cost', default=0, max_digits=4, decimal_places=2,
        validators=[MinValueValidator(0)]
    )
    monster_catering_cost = models.DecimalField(
        verbose_name='Monster catering cost', default=0, max_digits=4, decimal_places=2,
        validators=[MinValueValidator(0)]
    )
    catering_name = models.CharField(max_length=250)
    catering_contact_email = models.EmailField()

    subpage_types = []

    content_panels = Page.content_panels + [
        FieldPanel('event_date'),
        FieldPanel('intro'),
        FieldPanel('description'),
        FieldPanel('details'),
        FieldPanel('image'),
        FieldPanel('player_limit'),
        FieldPanel('monster_limit'),
        FieldPanel('player_cost'),
        FieldPanel('monster_cost'),
        FieldPanel('player_catering_cost'),
        FieldPanel('monster_catering_cost'),
        FieldPanel('catering_name'),
        FieldPanel('catering_contact_email'),
    ]

    @property
    def all_bookings(self):
        return EventBooking.objects.filter(event=self)

    @property
    def player_bookings(self):
        return EventBooking.objects.filter(event=self, player_type=EventBooking.PLAYER)

    @property
    def monster_bookings(self):
        return EventBooking.objects.filter(event=self, player_type=EventBooking.MONSTER)

    @property
    def staff_bookings(self):
        return EventBooking.objects.filter(event=self, player_type=EventBooking.STAFF)

    @property
    def has_max_players(self):
        return len(self.player_bookings) >= self.player_limit

    @property
    def has_max_monsters(self):
        return len(self.monster_bookings) >= self.monster_limit

    @property
    def is_concluded(self):
        return date.today() >= self.event_date

    def get_context(self, request, *args, **kwargs):
        context = super().get_context(request)
        booking_form = EventBookingForm()
        context['booking_form'] = booking_form
        context['player_bookings'] = self.player_bookings
        context['monster_bookings'] = self.monster_bookings
        context['paypal_client_id'] = settings.PAYPAL_CLIENT_ID
        context['has_max_players'] = self.has_max_players
        context['has_max_monsters'] = self.has_max_monsters
        context['is_concluded'] = self.is_concluded

        append_sidebar_to_context(context)

        return context


class EventEmail(models.Model):
    event = models.ForeignKey('EventPage', on_delete=models.PROTECT)
    player_types = models.CharField(max_length=8, choices=EventBooking.PLAYER_TYPES + [('A', 'All')])
    email_content = models.TextField()

events/forms.py
from django.forms.widgets import Select
from wagtail.admin.forms import WagtailAdminModelForm

from events.models import EventEmail


class EventEmailForm(WagtailAdminModelForm):
    class Meta:
        model = EventEmail
        fields = ['event','player_types', 'email_content']
        widgets = {
            'event': Select()
        }

events/views.py
import logging

from django.conf import settings
from django.contrib import messages
from django.core.mail import send_mass_mail
from django.http import HttpResponseBadRequest, HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from wagtail.contrib.modeladmin.options import ModelAdmin

from events.models import EventBookingForm, EventPage, EventBooking
from events.forms import EventEmailForm


logger = logging.getLogger(__name__)

# Create your views here.
def validate_event_form(request):
    if request.method != 'POST':
        return HttpResponseBadRequest('Method not allowed')

    form = EventBookingForm(request.POST)
    event_id = request.POST['event_id']

    try:
        event = EventPage.objects.get(id=event_id)
        if event.is_concluded:
            return HttpResponse(
                content=f'{"event_error": "event_id ${event_id} concluded"}',
                content_type='application/json',
                status=401
            )
    except EventPage.DoesNotExist:
        return HttpResponse(
            content=f'{"event_error": "event_id ${event_id} does not exist"}',
            content_type='application/json', status=401
        )

    if not form.is_valid():
        return HttpResponse(content=form.errors.as_json(), content_type='application/json', status=401)

    return HttpResponse(content=True, content_type='application/json')


def submit_event_booking(request):
    if request.method != "POST":
        return HttpResponseBadRequest('Method not allowed')

    data = request.POST
    event = EventPage.objects.get(id=data['event_id'])

    booking = EventBooking()
    booking.event = event

    booking.first_name = data['first_name'].capitalize()
    booking.last_name = data['last_name'].capitalize()
    booking.email = data['email']
    booking.contact_number = data['contact_number']
    booking.lt_player_id = data['lt_player_id'] if data['lt_player_id'] != '' else None
    booking.player_type = data['player_type']
    booking.character_name = data['character_name'].capitalize() if data['character_name'] != '' else None
    booking.character_faction = data['character_faction'] if data['character_faction'] != '' else None
    booking.emergency_contact_name = data['emergency_contact_name'].capitalize()
    booking.emergency_contact_number = data['emergency_contact_number']
    booking.home_address = data['home_address']
    booking.medical_information = data['medical_information']

    booking.is_catering = False
    booking.has_paid = False

    if 'is_catering' in data and data['is_catering'] == 'on':
        booking.is_catering = True

    if 'has_paid' in data and data['has_paid'] == 'on':
        booking.has_paid = True

    try:
        booking.save()

        messages.success(
            request,
            f'Your booking has been successful! We look forward to seeing you at the event. Booking name: {booking.first_name} {booking.last_name}, Booking type: {booking.get_player_type_display()}',
            'is-success',
        )
    except Exception as e:
        messages.error(request, 'There has been an unresolvable error. If you have paid via paypal, please contact '
                                'the Jackals Faction staff with your details.', 'is-danger')
        logger.error(f'Error saving booking: {e}', exc_info=e)

    return HttpResponseRedirect(event.url)


class EventBookingAdmin(ModelAdmin):
    model = EventBooking
    base_url_path = 'bookings'
    menu_label = 'Event Bookings'
    menu_icon = 'list-ul'
    menu_order = 300
    add_to_settings_menu = False
    exclude_from_explorer = False
    add_to_admin_menu = True
    list_display = (
        'id',
        'first_name',
        'last_name',
        'email',
        'contact_number',
        'lt_player_id',
        'player_type',
        'character_name',
        'character_faction',
        'is_catering',
        'has_paid',
    )
    list_filter = ('player_type', 'event', )
    list_export = (
        'first_name',
        'last_name',
        'email',
        'contact_number',
        'lt_player_id',
        'player_type',
        'character_name',
        'character_faction',
        'is_catering',
        'has_paid',
        'emergency_contact_name',
        'emergency_contact_number',
        'home_address',
        'medical_information',
    )
    search_fields = ('id', 'email', 'first_name', 'last_name', 'lt_player_id', )


def event_email_view(request):
    if request.method == 'POST':
        try:
            event = EventPage.objects.get(id=request.POST['event'])
            recipient_types = request.POST['player_types']
            email_content = request.POST['email_content']

            if recipient_types == '':
                raise Exception('No recipient type')

            if email_content == '':
                raise Exception('No email content')

            if recipient_types == EventBooking.PLAYER:
                recipients = event.player_bookings
            elif recipient_types == EventBooking.MONSTER:
                recipients = event.monster_bookings
            elif recipient_types == EventBooking.STAFF:
                recipients = event.staff_bookings
            else:
                recipients = event.all_bookings

            recipient_list = list(recipients.values_list('email', flat=True))

            email_subject = f"Jackal Event - {event.title}"

            email_tuple = (email_subject, email_content, settings.EMAIL_HOST_USER, recipient_list)

            send_mass_mail((email_tuple,), fail_silently=False)

            messages.success(request, 'Email sent')
        except EventPage.DoesNotExist:
            messages.error(request, 'Event does not exist')
        except Exception as e:
            messages.error(request, f'There was an error sending the email - {e}')
            logger.error(f'Error sending email: {e}', exc_info=e)


    return render(request, 'wagtailadmin/generic/form.html', context={
        'page_title': 'Event Email',
        'header_icon': 'mail',
        'form': EventEmailForm,
        'submit_button_label': 'Submit',
    })

events/templates/events/event_page.html
{% extends "base.html" %}

{% load wagtailcore_tags wagtailimages_tags %}
{% load custom_filters %}
{% load static %}

{% block body_class %}template-blogpage{% endblock %}

{% block hero %}
  {% image page.image original as main_image %}
  <section class="hero hero-img is-medium" style="background-image:url({{ main_image.url }})">
    <div class="hero-body"></div>
  </section>
{% endblock %}

{% block content %}
  <div class="content">
    <h1 class="title is-1" id="event-name">{{ page.title }}</h1>
    <p class="subtitle help">{{ page.event_date }}</p>

    {% if messages %}
      {% for message in messages %}
        <article class="message {% if message.tags %}{{ message.tags }}{% endif %}">
          <div class="message-body">
            {{ message }}
          </div>
        </article>
      {% endfor %}
    {% endif %}

    {% if booking_form.non_field_errors %}
      <article class="message is-danger">
        <div class="message-body">{{ booking_form.non_field_errors }}</div>
      </article>
    {% endif %}

    <p class="intro is-italic is-size-5">{{ page.intro }}</p>

    {{ page.description|richtext }}

    {{ page.details|richtext }}

    {% if is_concluded  %}
      <div class="message is-danger">
        <div class="message-body">
          <p>This event has concluded and is no longer able to be booked</p>
        </div>
      </div>
    {% elif has_max_players and has_max_monsters %}
      <div class="message is-danger">
        <div class="message-body">
          <p>We're sorry, this event currently has the maximum amount of players and monsters. Please check back later to see if the limits increase.</p>
        </div>
      </div>
    {% else %}
      <h3 class="title is-3">Booking Form</h3>

      {% if has_max_players %}
        <div class="message is-warning">
          <div class="message-body">
            <p>Please note, we have currently reached the maximum amount of player spaces available for this event, but you can still book as a monster. Please check back later to see if the player limit increases.</p>
          </div>
        </div>
      {% endif %}

      {% if has_max_monsters %}
        <div class="message is-warning">
          <div class="message-body">
            <p>Please note, we have currently reached the maximum amount of monster spaces available for this event, but you can still book as a player. Please check back later to see if the monster limit increases.</p>
          </div>
        </div>
      {% endif %}

      <noscript>
        <div class="message is-danger">
          <div class="message-body">
            <p>Sorry - this booking form requires JavaScript to be enabled in order to function. Please contact the Jackals faction staff in order to book this event.</p>
          </div>
        </div>
      </noscript>

      <form class="form" id="booking_form" action="/submit-event-booking/" method="post">
        {% csrf_token %}

        <input type="hidden" name="event_id" value="{{ page.id }}" />

        <div class="columns">
          <div class="column">
            <div class="field">
              <label class="label">{{ booking_form.first_name.label_tag }}*</label>
              <div class="control">
                {{ booking_form.first_name|addclass:'input' }}
              </div>
              {% if booking_form.first_name.errors %}
                <p class="help is-danger">{{ booking_form.first_name.errors }}</p>
              {% endif %}
            </div>
          </div>
          <div class="column">
            <div class="field">
              <label class="label">{{ booking_form.last_name.label_tag }}*</label>
              <div class="control">
                {{ booking_form.last_name|addclass:'input' }}
              </div>
              {% if booking_form.last_name.errors %}
                <p class="help is-danger">{{ booking_form.last_name.errors }}</p>
              {% endif %}
            </div>
          </div>
        </div>

        <div class="columns">
          <div class="column">
            <div class="field">
              <label class="label">{{ booking_form.email.label_tag }}*</label>
              <div class="control">
                {{ booking_form.email|addclass:'input' }}
              </div>
              {% if booking_form.email.errors %}
                <p class="help is-danger">{{ booking_form.email.errors }}</p>
              {% endif %}
            </div>
          </div>
          <div class="column">
            <div class="field">
              <label class="label">{{ booking_form.contact_number.label_tag }}*</label>
              <div class="control">
                {{ booking_form.contact_number|addclass:'input' }}
              </div>
              {% if booking_form.contact_number.errors %}
                <p class="help is-danger">{{ booking_form.contact_number.errors }}</p>
              {% endif %}
            </div>
          </div>
        </div>

        <div class="columns">
          <div class="column is-three-quarters">
            <div class="field">
              <label class="label">Lorien Trust player ID:</label>
              <div class="control">
                {{ booking_form.lt_player_id|addclass:'input' }}
              </div>
              <p class="help">{{ booking_form.lt_player_id.help_text }}</p>
              {% if booking_form.lt_pkayer_id.errors %}
                <p class="help is-danger">{{ booking_form.lt_player_id.errors }}</p>
              {% endif %}
            </div>
          </div>
          <div class="column">
            <div class="field">
              <label class="label" for="id_player_type">{{ booking_form.player_type.label_tag }}</label>
              <div class="control">
                <div class="select is-fullwidth">
                  <select name="player_type" id="id_player_type">
                    {% for player_choice in booking_form.player_type %}
                      {% if player_choice.choice_label != 'Staff' %}
                        {% if player_choice.choice_label == 'Player' and not has_max_players %}
                          {{ player_choice }}
                        {% endif %}
                        {% if player_choice.choice_label == 'Monster' and not has_max_monsters %}
                          {{ player_choice }}
                        {% endif %}
                      {% endif %}
                    {% endfor %}
                  </select>
                </div>
              </div>
              {% if booking_form.player_type.errors %}
                <p class="help is-danger">{{ booking_form.player_type.errors }}</p>
              {% endif %}
            </div>
          </div>
        </div>

        <div class="field">
          <h4 class="is-4">
            Event Price: <span id="player_cost" class="is-hidden">£{{ page.player_cost }} (Player)</span>
                         <span id="monster_cost" class="is-hidden">£{{ page.monster_cost }} (Monster)</span>
          </h4>
          <input type="hidden" name="player_cost" id="player_cost_value" value="{{ page.player_cost }}"/>
          <input type="hidden" name="monster_cost" id="monster_cost_value" value="{{ page.monster_cost }}">
        </div>

        <div class="columns is-hidden" id="character_details">
          <div class="column is-three-quarters">
            <div class="field">
              <label class="label">{{ booking_form.character_name.label_tag }}*</label>
              <div class="control">
                {{ booking_form.character_name|addclass:'input' }}
              </div>
              {% if booking_form.character_name.errors %}
                <p class="help is-danger">{{ booking_form.character_name.errors }}</p>
              {% endif %}
            </div>
          </div>
          <div class="column">
            <div class="field">
              <label class="label">{{ booking_form.character_faction.label_tag }}*</label>
              <div class="control">
                <div class="select is-fullwidth">
                  {{ booking_form.character_faction }}
                </div>
              </div>
              {% if booking_form.character_faction.errors %}
                <p class="help is-danger">{{ booking_form.character_faction.errors }}</p>
              {% endif %}
            </div>
          </div>
        </div>

        <div class="field">
          <label class="label">Catering</label>
          <p>Our events are catered at a nominal fee, but if you prefer you can manage your own provision. If you wish for
            us to provide you with food at the event, then please <b>tick below</b> and the cost will be added to the final
            booking price</p>
          <div class="control">
            <label class="checkbox" for="id_is_catering">
              {{ booking_form.is_catering }} <b>{{ booking_form.is_catering.label }}</b>
            </label>
          </div>
          {% if booking_form.is_catering.errors %}
            <p class="help is-danger">{{ booking_form.is_catering.errors }}</p>
          {% endif %}
          <p class="is-size-7">If you have any food requirements, please contact {{ page.catering_name }} ({{ page.catering_contact_email }}) to let them know.</p>
        </div>

        <div class="field">
          <h4 class="is-4">
            Catering Cost: <span class="is-hidden" id="player_catering_cost">£{{ page.player_catering_cost }} (Player)</span><span
            class="is-hidden" id="monster_catering_cost">£{{ page.monster_catering_cost }} (Monster)</span>
          </h4>
          <input type="hidden" name="player_catering_cost" id="player_catering_cost_value" value="{{ page.player_catering_cost }}"/>
          <input type="hidden" name="monster_catering_cost" id="monster_catering_cost_value" value="{{ page.monster_catering_cost }}">
        </div>

        <div class="columns">
          <div class="column">
            <div class="field">
              <label class="label">{{ booking_form.emergency_contact_name.label_tag }}*</label>
              <div class="control">
                {{ booking_form.emergency_contact_name|addclass:'input' }}
              </div>
              {% if booking_form.emergency_contact_name.errors %}
                <p class="help is-danger">{{ booking_form.emergency_contact_name.errors }}</p>
              {% endif %}
            </div>
          </div>
          <div class="column">
            <div class="field">
              <label class="label">{{ booking_form.emergency_contact_number.label_tag }}*</label>
              <div class="control">
                {{ booking_form.emergency_contact_number|addclass:'input' }}
              </div>
              {% if booking_form.emergency_contact_number.errors %}
                <p class="help is-danger">{{ booking_form.emergency_contact_number.errors }}</p>
              {% endif %}
            </div>
          </div>
        </div>

        <div class="field">
          <label class="label">{{ booking_form.home_address.label_tag }}</label>
          <div class="control">
            {{ booking_form.home_address|addclass:'textarea' }}
          </div>
          <p class="help">Please note, we only use this as a form of contact in an emergency, and is not required</p>
        </div>

        <div class="field">
          <label class="label">{{ booking_form.medical_information.label_tag }}</label>
          <div class="control">
            {{ booking_form.medical_information|addclass:'textarea' }}
          </div>
          <p class="help">Please note, we only use this in an emergency, and is not required</p>
        </div>

        <h3 class="is-3">
          Total Cost: £<span id="total_cost"></span>
          <div class="is-hidden">{{ booking_form.has_paid }}</div>
        </h3>

        <div class="field">
          <div class="control">
            <div id="smart-button-container">
              <div style="text-align: center;">
                <div id="paypal-button-container"></div>
              </div>
            </div>
          </div>
          <p class="help">* indicates a required field</p>
        </div>
      </form>
    {% endif %}

    <h3 class="title is-3">Attending Characters</h3>
    <p>Character count: {{ page.player_bookings|length }}, Monster count: {{ page.monster_bookings|length }}</p>

    {% if page.player_bookings %}
      <table class="table">
        <thead>
          <tr>
            <th>Character</th>
            <th>Faction</th>
          </tr>
        </thead>
        <tbody>
          {% for player in page.player_bookings %}
            <tr>
              <td>{{ player.character_name }}</td>
              <td>{{ player.get_character_faction_display }}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p><i>No characters have booked yet - be the first!</i></p>
    {% endif %}

    <p class="has-text-right push-link-right"><a class="link paint-link" href="{{ page.get_parent.url }}">Return to events</a></p>
  </div>
{% endblock %}

{% block extra_js %}
  <script src="https://www.paypal.com/sdk/js?client-id={{ paypal_client_id }}&enable-funding=venmo&currency=GBP" data-sdk-integration-source="button-factory"></script>
  <script src="{% static 'js/booking-form.js' %}"></script>
{% endblock %}

events/templates/events/events_index_page.html
{% extends "base.html" %}

{% load wagtailcore_tags wagtailimages_tags %}

{% block body_class %}template-eventsindexpage{% endblock %}

{% block content %}
  <div class="content">
    <h1 class="title is-1">{{ page.title }}</h1>

    <div class="block intro">{{ page.intro|richtext }}</div>
  </div>

  {% if events %}
    {% for event in events %}
      {% with event=event.specific %}
        <a class="box" href="{% pageurl event %}">
          <div class="media">
            <div class="media-left is-hidden-mobile">
              <figure class="image is-128x128">
                {% image event.image fill-128x128 %}
              </figure>
            </div>
            <div class="media-content">
              <h2 class="title is-2">{{ event.title }}</h2>
              <p class="subtitle help">{{ event.event_date }}</p>
              <p>{{ event.intro|richtext }}</p>
            </div>
          </div>
        </a>
      {% endwith %}
    {% endfor %}
  {% else %}
    <p><i>Sorry, there are no events to display right now</i></p>
  {% endif %}
{% endblock %}